apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-example
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: postgres-example
    server: 'https://kubernetes.default.svc'
  syncPolicy: {}
  source:
    path: postgres-example/
    repoURL: https://github.com/dhinakar2707/argocd-aop.git
    targetRevision: main
    directory:
      recurse: true
    # helm specific config
    helm:
      # Release name override (defaults to application name)
      releaseName: usage-postgres

      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
      - values.yaml
