kind: Secret
apiVersion: v1
metadata:
  name: vault-example
  annotations:
    avp.kubernetes.io/path: "secret/aop/application"
type: Opaque
stringData:
  username: <username>
  password: <password>
  postgresPassword: <postgresPassword>
  database: <database>
