apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dn-postgres-example
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: 'secrets/aop/data/application'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy: {}
  source:
    path: dn-postgres-example
    repoURL: https://github.com/dhinakar2707/argocd-aop.git
    targetRevision: HEAD
    # helm specific config
    helm:
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      parameters:
      - name: auth.postgresPassword
        value: <postgresPassword>
      - name: auth.username
        value: <username>
      - name: auth.password
        value: <password>
      - name: auth.database
        value: <database>
