apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-example
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: postgres-example
    server: 'https://kubernetes.default.svc'
  syncPolicy: {}
  source:
    path: postgres-example
    repoURL: https://github.com/dhinakar2707/argocd-aop.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f value.yaml
