# Vault Configuration Secret
apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
data:
  VAULT_ADDR: aHR0cDovL3ZhdWx0LmR1LmFvcC1kZXYuYXdzLmFjdGlhbmRhdGFjbG91ZC5jb206ODIwMA==
  AVP_AUTH_TYPE: dG9rZW4=
  AVP_AUTH_TOKEN: aHZzLkFTaHdubUdhTDZ2ZmZnaHJ1Y3lVUzJYcA==
  AVP_TYPE: dmF1bHQ=
